version: '3'
services:
  redis:
    image: "redis"
    restart: always
  web:
    depends_on:
      - redis
    restart: always
    build: .
    ports:
      - "5000:8080"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379